### ISSUE TITLE
user-based-cf asymmetric similarity matix

### ISSUE THREAD

**Issue by goodcheer** [ikatsov/tensor-house#6]
Given that the Pearson correlation coefficient is symmetric: corr(X,Y) = corr(Y,X),
I don't understand how `user_similarity` in your [notebook](https://github.com/ikatsov/tensor-house/blob/master/recommendations/user-based-cf.ipynb) matrix is asymmetry.

**Comment by ikatsov** [comment]
This was a bug, fixed in commit 9308494 
Thanks for reporting this.
